name: 'silverscreen'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  silverscreen:  # Match the project name (lowercase)
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table